// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";

export interface Activity { start_datetime: string, end_datetime: string, description: string, projects: Array<string>, actions: Array<Action>, }