// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AllAggregate } from "./AllAggregate";
import type { DailyAggregate } from "./DailyAggregate";

export interface Aggregates { daily: Array<DailyAggregate>, all: AllAggregate, }