// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";

export interface AllAggregate { total_minutes: bigint, project_minutes: Record<string, bigint>, action_minutes: Record<Action, bigint>, }