// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";

export interface Filter { min_date: string, max_date: string, free_text: string, projects: Array<string>, actions: Array<Action>, }