// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Activities } from "./Activities";
import type { ActivitiesAggregate } from "./ActivitiesAggregate";
import type { Filter } from "./Filter";
import type { ScaleXSegments } from "./ScaleXSegments";
import type { YActivities } from "./YActivities";

export interface Graph { all_activities: Activities, activities_aggregate: ActivitiesAggregate, applied_filter: Filter, filtered_per_scale_x_segments: ScaleXSegments, filtered_per_scale_y_activities: YActivities, }