// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scale } from "./Scale";
import type { XSegment } from "./XSegment";

export interface ScaleXSegments { values: Record<Scale, Array<XSegment>>, index: Record<Scale, Record<string, number>>, }