// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scale } from "./Scale";
import type { XSegment } from "./XSegment";

export type ScaleXSegments = Record<Scale, Array<XSegment>>;